services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
